//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECTunes.Database.ConfigLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signal
    {
        public int carId { get; set; }
        public int signalId { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public int startbit { get; set; }
        public int size { get; set; }
        public string format { get; set; }
        public string signed { get; set; }
        public Nullable<double> factor { get; set; }
        public Nullable<int> offset { get; set; }
        public Nullable<double> min { get; set; }
        public Nullable<int> max { get; set; }
        public Nullable<int> match { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
